### ISSUE TITLE
prov.summarize.run to have a snapshot.size parameter?

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/provSummarizeR#28]
Would it be a good idea to add a `snapshot.size` parameter to prov.summarize.run?

**Comment by RoseSheehan** [comment]
Hi Elizabeth! What additional functionality would you like provided with this feature? My understanding is that you can already include the `snapshot.size` parameter to be passed through to prov.run (through `...`). Is there another way you would like `snapshot.size` to be used in prov.summarize.run? Thanks!

**Comment by RoseSheehan** [comment]
Decided to leave `snapshot.size` in `...` and update provDebugR to match by removing `snapshot.size` parameter there.
