### ISSUE TITLE
Provenance summaries for console sessions

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/provSummarizeR#9]
In console mode, the current version of rdt/rdtLite does not always collect the correct information (or any information) for sourced scripts, inputs, outputs, and errors, so (for now at least) provenance summaries for console sessions should probably be limited to environment and library information.

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/provSummarizeR/pull/10/commits/76f373e481e27cfacb6ef351ac17487cf842a82f
